sonar.projectKey=rasuvaeff_yii3-seo
sonar.organization=rasuvaeff

sonar.sources=src
sonar.tests=tests

sonar.php.coverage.reportPaths=build/coverage.xml
sonar.sourceEncoding=UTF-8

sonar.coverage.exclusions=tests/**,config/**,examples/**
